---
title: "중간고사"
author: "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  __________학과 학번__________ 이름__________"
date: "2017-04-18"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#### 1. Dice

`die <- 1:6` 를 실행하였다. 다음 물음에 답하시오.


1.1 다음 코드 중 에러 메시지가 나올 것으로 예상되는 것은?

가. `die + 1`

나. `die + 1:2`

다. `die + 1:3`

라. `die + 1:4`

1.2 다음 중 그 결과가 다른 것을 하나 고르시오.

가. `die * die`

나. `die ^ 2`

다. `die ** 2`

라. `die %*% die`

1.3 `die / die` 의 계산 결과는 콘솔에 어떻게 나타나는가?

가. `1`

나. `[1] 1`

다. `1 1 1 1 1 1`

라. `[1] 1 1 1 1 1 1`

1.4 `die`의 각 원소를 5로 나눈 나머지를 나타내는 코드는 어느 것인가?

가. `die %% 5`

나. `die %/% 5`

다. `die %*% 5`

라. `die %o% 5`

1.5 사칙 연산자 중 `*` 에 대한 도움말을 구하고자 할 때 옳지 않은 것은?

가. `help(*)`

나. `help("*")`

다. `?`&#96;`*`&#96;

라. `?"*"`

1.6 다음 중 나머지 셋과 다른 연산을 수행하고 있는 것은?

가. `die %% 2`

나. `"%%"(die, 2)`

다. &#96;`%%`&#96;`(die, 2)`

라. &#96;`%%`&#96;`(2, die)`

1.7 공평한 주사위를 두 번 굴릴 때 나오는 결과를 표현한 코드로 적절한 것은? 

가. `sample(2, die)`

나. `sample(die, 2, replace = TRUE)`

다. `sample(die, 2, replace = FALSE)`

라. `sample(2, die, replace = TRUE)`

1.8 `roll2`를 다음과 같이 정의한 함수라 할 때, 

```
roll2 <- function(bones) {
  dice <- sample(bones, size = 2, replace = TRUE)
  sum(dice)
}
```
어떤 경우에 에러가 출력되는가?

가. `roll2(bones = 1:4)`

나. `roll2(bones = 1:5)`

다. `roll2(1:20)`

라. `roll2()`

1.9 위에서 정의한 `roll2`를 나중에 다시 불러들여 사용하기 위하여 저장할 때 적절한 코드는?

가. `dump(list = "roll2", file = "./roll2.R")`

나. `save(list = "roll2", file = "./roll2.R")`

다. `save.image(file = "./roll2.R")`

라. `write(list = "roll2", file = "./roll2.R")`

1.10 위와 같이 저장한 `roll2`를 불러들이는 코드는 무엇인가? 작업디렉토리와 저장한 티덱토리가 같다고 가정하자.

가. `read("./roll2.R")`

나. `source("./roll2.R")`

다. `load("./roll2.R")`

라. `get("./roll2.R")`

#### 2. Simulation 

2.1 공평한 주사위 두 개를 던져 합을 구하는 게임을 20번 반복하는 코드는 다음 중 어느 것인가? 위에서 정의한 `roll2`를 이용하시오. 단, `roll2`는 위에 정의한 대로 임.

가. `replicate(20, roll2())`

나. `replicate(20, roll2(bones = 1:6))`

다. `replicate(roll2(), 20)`

라. `replicate(roll2(bones = 1:6), 20)`

2.2 위의 실험을 1만번 반복하고, 그 결과를 `rolls`에 저장한 후 `ggplot` 패키지을 이용하여 간단한 히스토그램으로 나타내고자 한다. `ggplot`패키지는 설치되어 있고 `library`에 등록되어 있을 때 자료 특성에 비추어 가장 적절한 코드는?

가. `plot(rolls)`

나. `plot(rolls, binwidth = 1)`

다. `qplot(rolls)`

라. `qplot(rolls, binwidth = 1)`

2.3 `roll`함수를 편집하여 확률 조건을 추가한 `roll.w`를 만들려고 할 때 필요한 코드는? (단, 여기서 `;` 는 그 다음 코드를 이어서 수행하라는 것이다.)

가. `roll.w <- roll ; fix(roll.w)`

나. `roll.w <- roll ; vi(roll.w)`

다. `roll <- roll.w ; fix(roll.w)`

라. `roll <- roll.w ; vi(roll.w)`


#### 3. R Objects

3.1 `is.vector(5)` 의 답은 무엇인가?

가. `TRUE`

나. `FALSE`

다. `Yes`

라. `No`

3.2 위에서 저장해 놓은 `die`에 대해서 `typeof(die)`의 값은 무엇인가?

가. `"logical"`

나. `"integer"`

다. `"double"`

라. `"complex"`

3.4 `attributes(die)` 를 수행했더니 `$names` 항목이 발견되었다. 이 속성을 없애고자 할 때 적당한 코드는?

가. `names(die) <- ""`

나. `names(die) <- NA`

다. `names(die) <- NULL`

라. `names(die) <- NaN`

3.5 `dim(die) <- c(2, 3)`를 수행하였을 때 `class(die)` 는 무엇인가?

가. `[1] "integer"`

나. `[1] "vector"`

다. `[1] "matrix"`

라. `[1] "array"`

3.6 `today <- Sys.Date() ; class(today)` 의 결과는?

가. `[1] "integer"`

나. `[1] "Date"`

다. `[1] "matrix"`

라. `[1] "array"`

3.7 `gender <- factor(c("male", "female", "female", "male"))` 를 수행하고 `unclass(gender)`를 수행하면 그 결과는?

가. `[1] 2 1 1 2`

나. `[1] "integer"`

다. 

```
[1] male   female female male  
Levels: female male
```

라.  

```
$levels
[1] "female" "male"  

$class
[1] "factor"
```
